In [1]:
import numpy as np
from scipy.sparse import random, csr_matrix
from scipy.sparse.linalg import spsolve

# Generar matrices dispersas aleatorias
A = random(1000, 1000, density=0.1, format='csr')  # Matriz A dispersa
B = random(1000, 1000, density=0.1, format='csr')  # Matriz B dispersa

# Multiplicación de matrices dispersas
C = A.dot(B)

print("Matriz C resultante de la multiplicación:")
print(C)


Matriz C resultante de la multiplicación:
  (0, 57)	0.6192065437333057
  (0, 9)	1.1340091741367377
  (0, 988)	1.526887018321557
  (0, 940)	0.6178168412021585
  (0, 866)	2.3718945445946904
  (0, 202)	1.962861872395299
  (0, 703)	1.4533888246435405
  (0, 858)	1.754078512035334
  (0, 756)	0.5604946040677752
  (0, 7)	0.8635608910344257
  (0, 587)	3.0873580133075396
  (0, 996)	2.311667453359464
  (0, 846)	1.7759716992478447
  (0, 29)	3.300009091236311
  (0, 311)	2.322186955279797
  (0, 994)	2.3655848875322563
  (0, 859)	2.6830106204680564
  (0, 735)	2.947415072502139
  (0, 313)	1.798263744164318
  (0, 935)	1.2512879981878116
  (0, 875)	4.345826472224063
  (0, 711)	0.6817840904641783
  (0, 606)	0.5369344551025964
  (0, 782)	0.595015151919319
  (0, 455)	0.17394038639931061
  :	:
  (999, 262)	2.267619218958057
  (999, 247)	3.5168709992655156
  (999, 235)	3.849900265377587
  (999, 228)	2.5326652509359677
  (999, 226)	2.455660388216412
  (999, 222)	2.1956215072603635
  (999, 219)	3.9168795048428

In [2]:
C_dense = C.toarray()
print(C_dense)


[[3.96112683 3.10432771 1.09376614 ... 0.17582337 1.7705931  1.47469706]
 [1.84112651 1.70676824 1.77792824 ... 3.27512836 2.76933922 3.32712554]
 [3.19988108 1.70936383 5.15608306 ... 2.65004737 1.85740683 2.24576642]
 ...
 [1.9330372  3.67806153 3.03457509 ... 2.86549965 5.38712471 2.0025712 ]
 [1.0301613  1.69357369 0.54540717 ... 2.44513448 2.37575839 3.05597595]
 [3.59962833 2.58520809 3.8953832  ... 3.20702415 3.49654601 4.52016955]]
